# Generated by Django 5.2.7 on 2025-10-23 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Equipo',
                'verbose_name_plural': 'Categorías de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_REPARACION', 'En Reparación'), ('DADO_DE_BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.categoriaequipo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perfil', models.CharField(choices=[('EMPLEADO', 'Empleado'), ('JEFE_AREA', 'Jefe de Área'), ('RH', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas/IT'), ('ADMIN', 'Administrador')], max_length=20, verbose_name='Tipo de Perfil')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='Número de Empleado')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('dias_vacaciones_anuales', models.PositiveIntegerField(default=20, verbose_name='Días de Vacaciones Anuales')),
                ('dias_vacaciones_usados', models.PositiveIntegerField(default=0, verbose_name='Días de Vacaciones Usados')),
                ('dias_vacaciones_extraordinarios', models.PositiveIntegerField(default=0, verbose_name='Días de Vacaciones Extraordinarios Usados')),
                ('dias_vacaciones_acumulados', models.PositiveIntegerField(default=0, verbose_name='Días de Vacaciones Acumulados del Año Anterior')),
                ('ultimo_reset_vacaciones', models.DateField(blank=True, null=True, verbose_name='Último Reset de Vacaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.departamento', verbose_name='Departamento')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.perfil', verbose_name='Supervisor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento_dirigido', to='empleados.perfil', verbose_name='Jefe de Departamento'),
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('condicion_entrega', models.CharField(blank=True, max_length=200, verbose_name='Condición al Entregar')),
                ('condicion_devolucion', models.CharField(blank=True, max_length=200, verbose_name='Condición al Devolver')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='empleados.equipo', verbose_name='Equipo')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to='empleados.perfil', verbose_name='Asignado Por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='empleados.perfil', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('dias_solicitados', models.PositiveIntegerField(verbose_name='Días Solicitados')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Vacación Normal'), ('EXTRAORDINARIA', 'Vacación Extraordinaria'), ('EMERGENCIA', 'Vacación de Emergencia')], default='NORMAL', max_length=20, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('PENDIENTE_JEFE', 'Pendiente Jefe de Área'), ('APROBADO_JEFE', 'Aprobado por Jefe'), ('RECHAZADO_JEFE', 'Rechazado por Jefe'), ('PENDIENTE_RH', 'Pendiente RH'), ('APROBADO_RH', 'Aprobado por RH'), ('RECHAZADO_RH', 'Rechazado por RH'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_JEFE', max_length=20, verbose_name='Estado')),
                ('comentarios_jefe', models.TextField(blank=True, verbose_name='Comentarios del Jefe')),
                ('comentarios_rh', models.TextField(blank=True, verbose_name='Comentarios de RH')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_aprobacion_jefe', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación Jefe')),
                ('fecha_aprobacion_rh', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación RH')),
                ('aprobado_por_jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas_jefe', to='empleados.perfil', verbose_name='Aprobado por Jefe')),
                ('aprobado_por_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas_rh', to='empleados.perfil', verbose_name='Aprobado por RH')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='empleados.perfil', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Red/Conectividad'), ('ACCESO', 'Acceso/Permisos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Dispositivo Afectado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('descripcion', models.TextField(verbose_name='Descripción del Problema')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución Aplicada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='empleados.perfil', verbose_name='Asignado A')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='empleados.perfil', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
