# Generated by Django 5.2.7 on 2025-11-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='aprobado_por_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas_admin', to='empleados.perfil', verbose_name='Aprobado por Administrador'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='comentarios_admin',
            field=models.TextField(blank=True, verbose_name='Comentarios del Administrador'),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='fecha_aprobacion_admin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación Administrador'),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_JEFE', 'Pendiente Jefe de Área'), ('PENDIENTE_ADMIN', 'Pendiente Administrador'), ('APROBADO_JEFE', 'Aprobado por Jefe'), ('APROBADO_ADMIN', 'Aprobado por Administrador'), ('RECHAZADO_JEFE', 'Rechazado por Jefe'), ('RECHAZADO_ADMIN', 'Rechazado por Administrador'), ('PENDIENTE_RH', 'Pendiente RH'), ('APROBADO_RH', 'Aprobado por RH'), ('RECHAZADO_RH', 'Rechazado por RH'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_JEFE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Vacación Normal'), ('EXTRAORDINARIA', 'Vacación Extraordinaria'), ('EMERGENCIA', 'Vacación Extraordinaria')], default='NORMAL', max_length=20, verbose_name='Tipo'),
        ),
    ]
