# Generated by Django 5.2.7 on 2025-12-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_solicitudvacaciones_aprobado_por_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('tipo_movimiento', models.CharField(choices=[('VACACIONES_TOMADAS', 'Vacaciones tomadas'), ('VACACIONES_ANTES_REGISTRO', 'Vac. tomadas antes del registro del empleado'), ('ANIVERSARIO_LABORAL', 'Aniversario laboral al finalizar I'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('OTRO', 'Otro')], default='VACACIONES_TOMADAS', max_length=50, verbose_name='Tipo de Movimiento')),
                ('fecha_registro', models.DateField(verbose_name='Fecha registro')),
                ('fecha_inicial', models.DateField(blank=True, null=True, verbose_name='Fecha inicial')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('tomadas', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Tomadas')),
                ('con_derecho', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Con derecho')),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Saldo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_vacaciones_creadas', to='empleados.perfil', verbose_name='Creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_vacaciones', to='empleados.perfil', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Historial de Vacaciones',
                'verbose_name_plural': 'Historial de Vacaciones',
                'ordering': ['empleado', 'fecha_registro', '-fecha_creacion'],
            },
        ),
    ]
