# Generated by Django 5.2.7 on 2025-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_historialvacaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dias_vacaciones_extraordinarios_ano_anterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Días Extraordinarios del Año Anterior (para restar del año actual)'),
        ),
    ]
