# Generated by Django 5.2.7 on 2025-12-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_perfil_dias_vacaciones_extraordinarios_ano_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='saldo_vacaciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo resultante de años anteriores (acumulado - gastado). Puede ser negativo o positivo.', max_digits=10, verbose_name='Saldo de Vacaciones (Años Anteriores - Gastado)'),
        ),
    ]
