# Generated by Django 5.2.7 on 2025-10-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_categoriaequipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='salario',
        ),
    ]
